title: "SLATE: a Super-Lightweight Annotation Tool for Experts"
description: A terminal-based text annotation tool written in Python.
show_downloads: true
google_analytics: UA-19179423-2
theme: jekyll-theme-cayman
